name: student_management_app
description: A Flutter app for managing students
publish_to: none
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.5.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
